name: CI Workflow

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ runner.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          if [[ "${{ runner.os }}" == "Linux" || "${{ runner.os }}" == "macOS" ]]; then
            pip install -r requirements.txt
          elif [[ "${{ runner.os }}" == "Windows" ]]; then
            pip install -r requirements.txt
          fi

      - name: Run tests on Linux or macOS
        if: startsWith(runner.os, 'Linux') || startsWith(runner.os, 'macOS')
        run: |
          echo "Running tests on Linux or macOS"
          pytest tests/

      - name: Run tests on Windows
        if: runner.os == 'Windows'
        run: |
          echo "Running tests on Windows"
          pytest tests/

      - name: Build application
        run: |
          echo "Building application..."
          # Add your build commands here

      - name: Notify on success
        if: success()
        run: |
          echo "Build and tests completed successfully!"
